# run ruby program

# copy from example_ui_api/Dockerfile (basic ruby/alpine/bundler dockerfile)

# idea, bundle ffmpeg to do some video correction commands (brightness / contrast / sharpness_on=true)
