source "https://rubygems.org"

# gem "oj"

gem "rake"

gem "roda"

gem "comma-api-rb", require: "comma-api-rb" # release
# gem "comma-api-rb", path: "../../", require: "comma-api-rb" # dev env

gem "puma"
